sudo: required
language: java
jdk: oraclejdk8

services:
  - docker
  
before_install:
  - chmod +x mvnw

env:
  global:
    - secure:"lahnl3VRdCc+pLVKAZm4Nk4/dhWbow9262gK3eGIgoykT31TcxiRY7C+VPCs8v8Esnojnt5hc8rowPBRoSjUmymNVf8JamMCyqlNnJ90pf2xvU75VTaYl4k8+waazJQCcAUGTXkcLTNGALF1MZXoQ51oQjST4xYZ8HpbicV0Dmx0YMynMUPbYUlA/vRqJq5IDK5Y8RAmvhZsu+JMaUDy1uwQ3KDHEQRNulmkzmNrNniu+DoP4IZ2+czwGrKhqQeAZhFr2rZ4KGEz7cRZJwUOHTix4JJ6g4RzUeix6zBrIdSTIAOdxgVP2gILc7Z5QteY7BZ3Hv3d8FD6OivLI8bFoRcc1ALSQ1yJ13bYf8sZpZw51dz8vcfAGLQTq03pNuA0+CvX66Nz/VNt7Q9QFPwjpHDvlB2O6zi+Zpx26dlK2b9Ux1DZOTrGFCdE+bSZKvNOCNIiPyliLKgKlQaUiS6waN6GYymqnyxkAbhnVIDpju6tWQShyi0xLTXO5rTpAqy7K2zZMGhxPLwUMurLegpFFxsWbpGl32xlO5p0qCmi0sWMbYLS6+ZwJySjqdisjs6c/rs7dXXD1EicYwCf5g6cBYSKZOGs3KFaRkTmf8kpW34GLOtLgAphKr+9SZOt85MKYvSAAqLeKA0vEFUPOjX8tpJXoUVdjSUx9zHcGsL0H+8="
    - secure:"bpZD3HP/ieT/uWi6c7E9W47+GfHrpjKJy+jDaJpBh3qX3Y85R0j1Rb+6wQa0/MtgUu6MJAyUHhR8x2YXS/P3Oh9IHrzL5OY4PvrkpHd8IEhMvT38b7vbqSLOLtSM0pK8hdqFQLHB9Y3EbiH4ukat5iURAcujThcQRWcvwzyslfO7oquXYqyyXJVusYiS56CSZT+v2TKemvQ6FUzo6Ye6PYMdqrmvZpcIhqAPl/u+EoKOc0jUryuH8Uu7VSL6xrGtjzRvf3H+Mp8qXzTlL98cs/+ftoTFa7fhSTOSICjMjUp3QD2dUw8Mkc8ClD8aVpkjpIy/KD/i+TZpCAZA83rAzPEzDRRvEvw7oTeMYeQjubL0zkX5LFKQEsBZPJ4Ljwed5D0OiKZSqzW2mXNtHBSNyNe13+6ghJ0WxloP12SKdiZe6X4mJ16y8iyOPJYDjlSv7VCchl6HXp3ftqItV5yz6tXne06vybnjlbsKMQ5IlFbmpWTbLhIJD3JsSDX/P7OpBeWp/+tB0bkq+qvgIBj8ztUWQTVNILiKHEmcjkNEYm3GfemebpZOpRjSVjhFCOcgjuvsb92B4lf7H7jW1edWt6HEIHfRxXBVnhMGT/ncBchU8zETlMCw+JVJIsXarbIwSLFoZPH14Vr5y+89/K/uREnkQBm0k/cHon8tPdd6tnQ="

script:
  - ./mvnw clean install

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
  - export IMAGE_NAME=npnitin/jpapi
  - docker build -t $IMAGE_NAME:$COMMIT .
  - docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
  - docker push $IMAGE_NAME
